name: dicoding_story
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  go_router: ^17.0.0
  google_fonts: ^6.3.2
  logging: ^1.3.0
  window_manager: ^0.5.1
  palette_generator: ^0.3.3+7
  window_size_classes: ^1.1.0+1
  flutter_riverpod: ^3.0.3
  riverpod_annotation: ^3.0.3
  m3e_collection: ^0.3.7
  dynamic_color: ^1.8.1
  intl: ^0.20.2
  insta_assets_picker: ^3.4.0
  wechat_camera_picker: ^4.4.0
  crop_your_image: ^2.0.0
  image_picker_windows: ^0.2.2
  image_picker: ^1.2.1
  dio: ^5.9.0
  cached_network_image: ^3.4.1
  freezed_annotation: ^3.1.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  riverpod_generator: ^3.0.3
  build_runner: ^2.7.1
  custom_lint: ^0.8.0
  riverpod_lint: ^3.0.3
  http_mock_adapter: ^0.6.1
  freezed: ^3.2.3
  json_serializable: ^6.11.2
  mocktail: ^1.0.4
  mocktail_image_network: ^1.2.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/logo_light.png
    - assets/logo_dark.png
